TCCBarbearia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls'))
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, salvar, editar, deletar


urlpatterns = [
    path('', home),
    path('salvar/', salvar, name='salvar'), 
    path('editar/<int:pessoa_id>/', editar, name='editar'),
    path('deletar/<int:pessoa_id>/', deletar, name='deletar'),
]

core/models.py
from django.db import models

class Pessoa(models.Model):
    nome = models.CharField(max_length=100)
    data = models.DateField()
    hora = models.TimeField()
    # outros campos...

# Create your models here.

core/views.py
from datetime import date, datetime, timedelta
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Pessoa

def home(request):
    pessoa = Pessoa.objects.all()
    return render(request, "index.html", {"pessoa":pessoa})


def salvar(request):
    vnome = request.POST.get("nome")
    vdata = request.POST.get("data")
    vhora = request.POST.get("hora")
    
    # Converter a string da data e hora para objetos de data e hora
    data = datetime.strptime(vdata, "%Y-%m-%d").date()
    hora = datetime.strptime(vhora, "%H:%M").time()

     # Obter a data e hora atuais
    data_atual = date.today()
    hora_atual = datetime.now().time()

    # Verificar se a data é anterior à data atual
    if data < data_atual:
        messages.error(request, "Não é possível agendar para uma data anterior à data atual.")
        return redirect(home)
    
    # Verificar se a data é igual à data atual e a hora é anterior à hora atual
    if data == data_atual and hora < hora_atual:
        messages.error(request, "Não é possível agendar para um horário anterior ao horário atual.")
        return redirect(home)

    # Verificar se já existe uma pessoa agendada para a mesma data e hora
    agendamentos_existentes = Pessoa.objects.filter(data=data, hora=hora)
    if agendamentos_existentes.exists():
        messages.error(request, "Já existe um agendamento para essa data e hora.")
        return redirect(home)
    
    horarios_disponiveis = []
    if not agendamentos_existentes.exists():
        horarios_disponiveis.append(hora_atual.strftime("%H:%M"))
    
    """
    else:
        # Definir o horário de início e fim permitido para agendamento
        hora_inicio = datetime.strptime("07:00", "%H:%M").time()
        hora_fim = datetime.strptime("22:00", "%H:%M").time()

        # Verificar se a hora fornecida está dentro do intervalo permitido
        if hora < hora_inicio or hora > hora_fim:
            messages.error(request, "A hora de agendamento está fora do intervalo permitido.")
        else:
            # Calcular o próximo horário disponível com intervalo de 45 minutos
            prox_hora = hora
            while Pessoa.objects.filter(data=data, hora=prox_hora).exists():
                prox_hora = (datetime.combine(date.today(), prox_hora) + timedelta(minutes=45)).time()

                # Verificar se o próximo horário está fora do intervalo permitido
        if prox_hora > hora_fim:
            messages.error(request, "Não há horários disponíveis dentro do intervalo permitido.")
            return redirect(home)
    """

    # Gravar no banco de dados do Django
    Pessoa.objects.create(nome=vnome, data=data, hora=hora)
    messages.success(request, "Agendamento realizado com sucesso.")
    
    # Retorna no html para visualização 
    pessoa = Pessoa.objects.all()
    return render(request, "index.html", {"pessoa": pessoa, "horarios_disponiveis": horarios_disponiveis})

def editar(request, pessoa_id):
    pessoa = Pessoa.objects.get(id=pessoa_id)
    if request.method == 'POST':
        vnome = request.POST.get('nome')
        vdata = request.POST.get('data')
        vhora = request.POST.get('hora')

        data = datetime.strptime(vdata, '%Y-%m-%d').date()
        hora = datetime.strptime(vhora, '%H:%M').time()

        pessoa.nome = vnome
        pessoa.data = data
        pessoa.hora = hora
        pessoa.save()

        messages.success(request, 'Agendamento atualizado com sucesso.')
        return redirect(home)

    return render(request, 'editar.html', {'pessoa': pessoa})

def deletar(request, pessoa_id):
    pessoa = Pessoa.objects.get(id=pessoa_id)
    pessoa.delete()
    #messages.success(request, 'Agendamento deletado com sucesso.')
    return redirect(home)

core/templates/editar.html
<!DOCTYPE html>
<html lang="pt-bt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>
</head>
<body>
    {{pessoa.id}} - {{ pessoa.nome }} - {{ pessoa.data }} - {{ pessoa.hora }}

    <form action="{% url 'editar' pessoa.id %}" method="POST">
        {% csrf_token %}
        <label for="id_nome">Nome:</label>
        <input type="text" name="nome" id="id_nome" value="{{pessoa.nome}}">
        <br>
        <label for="id_data">Data:</label>
        <input type="date" name="data" id="id_data" value="{{pessoa.data }}">
        <br>
        <label for="id_hora">Hora:</label>
        <input type="time" name="hora" id="id_hora" value="{{pessoa.hora }} ">
        <br>
        <button type="submit" onclick="exibirAlerta()">Salvar</button>
    </form>

    
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
</head>
<body>

    <h2>Agendamento</h2>
    <form method="post" action="{% url 'salvar' %}">
        {% csrf_token %}
        <label for="id_nome">Nome:</label>
        <input type="text" name="nome" id="id_nome" required>
        <br>
        <label for="id_data">Data:</label>
        <input type="date" name="data" id="id_data" required>
        <br>
        <label for="id_hora">Hora:</label>
        <select name="hora" id="id_hora" {% if hora_selecionada %} disabled{% endif %}>
            <option value="" disabled selected>Selecione um horário</option>
        <!-- Adicione as opções de horários disponíveis -->
            {% if pessoa.hora == '07:00' %}selected{% endif %}
            <option value="07:00">07:00</option>
            <option value="07:45">07:45</option>
            <option value="08:30">08:30</option>
            <option value="09:15">09:15</option>
            <option value="10:00">10:00</option>
            <option value="10:45">10:45</option>
            <option value="11:30">11:30</option>
            <option value="12:15">12:15</option>
            <option value="13:00">13:00</option>
            <option value="13:45">13:45</option>
            <option value="14:30">14:30</option>
            <option value="15:15">15:15</option>
            <option value="16:00">16:00</option>
            <option value="16:45">16:45</option>
            <option value="17:30">17:30</option>
            <option value="18:15">18:15</option>
            <option value="19:00">19:00</option>
            <option value="19:45">19:45</option>
            <option value="20:30">20:30</option>
            <option value="21:15">21:15</option>
        </select>
        <button type="submit" >Salvar</button>
    </form>

    
    <h3>Lista de Pessoas Agendadas:</h3>
    <ul>
        {% for pessoa in pessoa %}
            <li>{{ pessoa.nome }} - {{ pessoa.data }} - {{ pessoa.hora }}</li>
            <td>
                <a href="{% url 'editar' pessoa.id %}">Editar</a>
                <a href="{% url 'deletar' pessoa.id %}">Deletar</a>
              </td>
        {% endfor %}
    </ul>



    <h3>Lista de horario disponivel:</h3>
    <ul>
        {% for horario in horarios_disponiveis %}
        <li>{{ horario }}</li>
        {% endfor %}
    </ul>
</body>
</html>